/**
 * 
 */
package net.eq2online.macros.scripting.api;

/**
 * Interface for objects which what to veto outbound messages generated by macros 
 *
 * @author Adam Mummery-Smith
 */
public interface IMessageFilter extends IMacrosAPIModule
{
	/**
	 * Called when a message generated by macros is added to the outbound queue (spam filter).
	 * Implementors can return FALSE to prevent this message being enqueued or TRUE to pass.
	 * 
	 * @param message
	 * @return
	 */
	public abstract boolean enqueueMessage(String message);
}
